version: "3"

networks:
  localstack_default:
    external: true

services:
  node:
    restart: always
    build: .
    ports:
      - 3002:3002
    volumes:
      - ./:/code
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27018:27018
    volumes:
      - mongodb:/data/
  swagger-ui:
    depends_on:
      - node
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "81:8081"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: /swagger/openapi.yaml
volumes:
  mongodb:
