version: "3"

networks:
  docker_network:
    driver: bridge
    name: docker_network

services:
  node:
    restart: always
    build: .
    ports:
      - 3002:3002
    volumes:
      - ./:/code
    depends_on:
      - mongo
    networks:
      - docker_network
  mongo:
    image: mongo
    restart: always
    command: mongod --port 27018
    ports:
      - 27018:27018
    volumes:
      - mongodb:/data/db
    expose:
      - 27018
    networks:
      - docker_network
  swagger-ui:
    depends_on:
      - node
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container_pedido
    ports:
      - "81:8081"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: /swagger/openapi.yaml
    networks:
      - docker_network
volumes:
  mongodb:
