export * from './authenticationFailed.exception';
export * from './base.exception';
export * from './cpfInvalido.exception';
export * from './dtoValidationError.exception';
export * from './isNotNaturalNumber.exception';
export * from './isPastDate.exception';
export * from './notNull.exception';
export * from './registroExistente.exception';
export * from './registroInexistente.exception';